# Generated by Django 4.2.5 on 2023-11-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaitudoabaixo', '0003_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='lastname',
            field=models.TextField(default=True, max_length=100),
        ),
    ]
