# Generated by Django 4.2.5 on 2023-11-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaitudoabaixo', '0005_alter_articles_image_alter_users_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('lastname', models.TextField(default='', max_length=100)),
                ('email', models.TextField(max_length=50)),
                ('password', models.TextField(max_length=100)),
            ],
        ),
    ]
