# Generated by Django 4.2.5 on 2023-11-14 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaitudoabaixo', '0009_alter_users_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
