# Generated by Django 4.2.5 on 2023-11-15 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaitudoabaixo', '0018_alter_othermodel_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='myUser',
        ),
    ]
