# Generated by Django 4.2.5 on 2023-11-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaitudoabaixo', '0019_delete_myuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
